<?php

namespace AppBundle\Repository;

/**
 * ProduitFactureRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class ProduitFactureRepository extends \Doctrine\ORM\EntityRepository
{
}
