<?php

namespace AppBundle\Repository;

/**
 * TypefactureRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class TypefactureRepository extends \Doctrine\ORM\EntityRepository
{
}
