services:
    app.form.type.user_client:
        class: AppBundle\Form\UserClientType
        tags:
            - { name: form.type }

    app.form.type.user_registration:
        class: UserBundle\Form\UserRegistrationType

    app.mailer:
        class: AppBundle\Services\Mailer
        arguments: ['@swiftmailer.mailer', '@templating.engine.twig']

#    app.form.type.user_profile:
#        class: AppBundle\Form\UserProfileType
#        parent: app.form.type.user

#    app.form.type.login:
#        class: UserBundle\Form\LoginFormType
#        tags:
#            - { name: form.type }
